config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get root to: 'application#hello'
  get 'pull', to: 'application#pull'
  get 'pull_item', to: 'application#pull_item'
  get 'purchase_item', to: 'application#purchase_item'
  get 'about', to: 'application#about'
  get 'account', to: 'application#account'
  get 'inventory', to: 'application#inventory'
  get 'disenchant', to: 'application#disenchant'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/drop.rb
# == Schema Information
#
# Table name: drops
#
#  id         :bigint           not null, primary key
#  end_time   :datetime         not null
#  start_time :datetime         not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Drop < ApplicationRecord
  has_many :drop_items

  alias_attribute :items, :drop_items

  def floor
    items.map(&:item).pluck(:value_usd).min
  end

  def ceiling
    items.map(&:item).pluck(:value_usd).max
  end

  def total_value
    items.map(&:item).pluck(:value_usd).reduce(0.0) { |sum, el| sum + el }
  end

  def items_in_drop
    items.count
  end

  def average
    total_value / items_in_drop
  end

  def count_pulled
    items.pulled.count
  end

  def count_remaining
    items_in_drop - count_pulled
  end

  def pullable?
    items.available.any?
  end

  def pull!
    return if items.available.empty?

    item = items.available.sample

    item.update(pulled: true)

    item
  end
end

app/models/drop_item.rb
# == Schema Information
#
# Table name: drop_items
#
#  id             :bigint           not null, primary key
#  pulled         :boolean          default(FALSE), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  drop_id        :bigint           not null
#  inventory_id   :bigint
#  item_id        :bigint           not null
#  transaction_id :bigint
#
# Indexes
#
#  index_drop_items_on_drop_id              (drop_id)
#  index_drop_items_on_drop_id_and_item_id  (drop_id,item_id) UNIQUE
#  index_drop_items_on_inventory_id         (inventory_id)
#  index_drop_items_on_item_id              (item_id)
#  index_drop_items_on_transaction_id       (transaction_id)
#
# Foreign Keys
#
#  fk_rails_...  (drop_id => drops.id)
#  fk_rails_...  (inventory_id => inventories.id)
#  fk_rails_...  (item_id => items.id)
#  fk_rails_...  (transaction_id => transactions.id)
#
class DropItem < ApplicationRecord
  belongs_to :drop
  belongs_to :item

  belongs_to :inventory, optional: true

  # validates :drop_id, uniqueness: { scope: :item_id }

  scope :pulled, -> { where(pulled: true) }
  scope :available, -> { where(pulled: false) }

  def to_s
    "#{item.name} ($#{item.value_usd})"
  end
end

app/models/inventory.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: inventories
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_inventories_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Inventory < ApplicationRecord
    belongs_to :user

    has_many :items, foreign_key: 'inventory_id', class_name: 'DropItem', dependent: :destroy
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id                :bigint           not null, primary key
#  name              :string(255)      default("item_placeholder"), not null
#  release_year      :integer
#  unique_identifier :string(255)
#  value_usd         :decimal(10, )    default(0), not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Item < ApplicationRecord
    has_one_attached :image
end

app/models/transaction.rb
# == Schema Information
#
# Table name: transactions
#
#  id           :bigint           not null, primary key
#  amount_usd   :decimal(10, )    default(0), not null
#  is_valid     :boolean
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  drop_item_id :bigint
#  user_id      :bigint           not null
#
# Indexes
#
#  index_transactions_on_drop_item_id  (drop_item_id)
#  index_transactions_on_user_id       (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (drop_item_id => drop_items.id)
#  fk_rails_...  (user_id => users.id)
#
class Transaction < ApplicationRecord
  before_create :check_account_balance

  has_one :drop_item

  def check_account_balance
    user = User.find(user_id) # Assuming `user_id` is an attribute of the model
    self.is_valid = user.account_balance.positive?
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  account_balance        :decimal(10, 2)   default(0.0), not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :inventory

  has_many :transactions
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :load_drop, only: %i[pull_item]
  # before_action :authenticate_user!, only: %i[pull_item]

  def hello
    @drop = Drop.last&.decorate

    render layout: 'layouts/application'
  end

  def about; end

  def pull; end

  def account; end

  def inventory; end

  def disenchant; end

  def pull_item
    balance = current_user.account_balance
    current_user.update!(account_balance: balance - 1)
    render json: { pulled: '1x booster box' }
    # @drop = Drop.create!
    # if @drop&.pullable?
    #   txn = Transaction.create!(user_id: current_user.id, amount_usd: 10.00)

    #   if txn.is_valid
    #     current_user.update!(account_balance: current_user.account_balance - 10)
    #     @item = @drop&.pull!
    #     @item.update!(inventory_id: current_user.inventory.id)
    #     txn.update!(drop_item: @item)
    #     @item = @item.item
    #     render
    #   else
    #     render json: { error: 'INSUFFICIENT_FUNDS' }, status: :unprocessable_entity
    #   end

    # else
    #   @error = 'UNAVAILABLE'
    #   render
    # end
  end

  def purchase_item
    item = Item.find_or_create_by(name: 'OP-01')
    drop = Drop.create!(start_time: Time.current, end_time: Time.current)
    DropItem.create!(item:, drop:)
    render
  end

  private

  def load_drop
    @drop = Drop.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= render 'shared/top_navbar' %>
    <%= render 'shared/sidebar' %>
    <h1>FAQ</h1>
    <h3>What is this?</h3>
    <div class='middle-section'>
      <h3>This is a TCG pull game!</h3>
    </div>
  </body>
</html>

app/views/application/account.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= render 'shared/top_navbar' %>
    <%= render 'shared/sidebar' %>
    <h1>Account</h1>
    <h3>User:</h3>
    <div class='middle-section'>
      <h3><%= current_user.email %></h3>
    </div>
    <h3>Account Balance:</h3>
    <div class='middle-section'>
      <h3>$<%= current_user.account_balance %> USD</h3>
    </div>
    <h3>Transactions:</h3>
    <div class='middle-section'>
      <ul>
        <% current_user.transactions.each do |transaction| %>
          <li><%= "#{transaction.created_at}, #{transaction.amount_usd}, #{transaction.drop_item}" %></li>
        <% end %>
      </ul>
    </div>
  </body>
</html>

app/views/application/disenchant.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= render 'shared/top_navbar' %>
    <%= render 'shared/sidebar' %>
    <h1>Disenchant</h1>
    <div class='middle-section'>
        <p>Coming Soon!</p>
    </div>
  </body>
</html>

app/views/application/hello.html.erb
<!DOCTYPE html>
<html>
  <body>
    <%= render 'shared/top_navbar' %>
    <%= render 'shared/sidebar' %>
    <div class="content">
      <div class="home-page-section"></div>
      <br>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="image-container">
              <%= image_tag('photo.png', alt: 'Description of the image' , size: '400x400' ) %>
            </div>
          </div>
        </div>
        <br>
        <div class="giveaway-section">
          <a href=<%= pull_path%>><button class="btn btn-xl btn-primary">Play Now</button></a>
        </div>
      </div>
    </body>
  </html>

app/views/application/inventory.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= render 'shared/top_navbar' %>
    <%= render 'shared/sidebar' %>
    <h1>Inventory</h1>
    <div class='middle-section'>
      <ul>
        <% DropItem.all.each do |item| %>
          <li><%= item.item.name %></li>
          <%= image_tag(url_for(item.item.image), size: "400") if item.item.image.attached? %>
        <% end %>
      </ul>
    </div>
  </body>
</html>

app/views/application/pull.html.erb
<!DOCTYPE html>
<html>
  <body>
    <%= render 'shared/top_navbar' %>
    <%= render 'shared/sidebar' %>
    <div class="content">
      <div class="home-page-section"></div>
      <br>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="image-container">
              <%= turbo_frame_tag "pull_frame" do %>
              <div class="image-container">
                <%= image_tag('photo.png', alt: 'Description of the image' , size: '400x400' ) %>
              </div>
              <!-- <div class="giveaway-section">
                <%= link_to "PULL!" , pull_item_path , class: "button", id: "pull-button" %>
              </div> -->
              <div class="giveaway-section">
                <%= link_to "Buy 1" , purchase_item_path , class: "button", id: "purchase-button" %>
              </div>
            <% end %>
            </div>
          </div>
        </div>
        <br>
      </div>
    </body>
  </html>

app/views/application/pull_item.html.erb
<%= turbo_frame_tag "pull_frame" do %>
  <% if @item %>
    <h1>YOU PULLED:</h1>
    <h2><%= @item&.name %>, $<%= @item&.value_usd %>, <%= @item&.unique_identifier %>, <%= @item&.release_year %></h2>
    <div class="image-container">
      <%= image_tag(url_for(@item.image), size: "400") if @item.image.attached? %>
    </div>
    <div class="giveaway-section">
      <%= link_to "PULL!" , pull_item_path , class: "button", id: "pull-button" %>
    </div>
  <% else %>
    <h1><%= @error %></h1>
  <% end %>
<% end %>

app/views/application/purchase_item.erb
<%= turbo_frame_tag "pull_frame" do %>
    <canvas id="gashaponCanvas" width="300" height="300"></canvas>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>tcgasha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <ul>
    <div class="icon-container">
      <li><%= link_to root_path do %>
        <i class="fas fa-home"></i>
      <% end %></li>
    </div>
    <div class="icon-container">
      <li><%= link_to inventory_path do %>
        <i class="fas fa-bolt"></i>
      <% end %></li>
    </div>
    <!-- <div class="icon-container">
      <li><%= link_to disenchant_path do %>
        <i class="fas fa-wand-magic-sparkles"></i>
      <% end %></li>
    </div> -->
    <!-- Add more sidebar options as needed -->
  </ul>
</div>

app/views/shared/_top_navbar.html.erb
<nav class="navbar">

  <div class="navbar-brand">
    <%= link_to 'tcgasha', root_path, class: 'navbar-item' %>
  </div>

  <div class="navbar-menu">
    <div class="navbar-end">
      <!-- <%= link_to 'FAQ', about_path, class: 'navbar-item' %> -->
      <!-- <%= link_to 'Account', account_path, class: 'navbar-item' %> -->

      <% if current_user %>
        <a class="navbar-item">Balance: <%= current_user.account_balance %></a>
        <a class="navbar-item"><%= current_user.email %></a>
        <%= link_to 'Logout' , destroy_user_session_path, method: :delete, class: 'navbar-item'  %>
      <% else %>
        <%= link_to 'Login' , new_user_session_path, class: 'navbar-item'  %>
        <%= link_to 'Sign up' , new_user_registration_path, class: 'navbar-item'  %>
      <% end %>
    </div>
  </div>

</nav>